import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";


const roboto = Roboto({
  style:["normal"],
  subsets: ['cyrillic']
})


const inter = Inter({
  subsets: ["cyrillic"]
})

export const metadata: Metadata = {
  title: "Petra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
